settings:
  title: 'Status Page'
  logo: logo-192x192.png # image in ./public/ folder
  url: 'https://status-page.eidam.dev' # used for Slack & Discord messages
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: tiktokez # unique identifier
    name: tiktokez.com
    description: 'TikTok Proper Embed' # default=empty
    url: 'https://www.tiktokez.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
    
  - id: instagramez # unique identifier
    name: instagramez.com
    description: 'Instagram Proper Embed' # default=empty
    url: 'https://www.instagramez.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

